version: '3.1'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      url: "jdbc:mariadb://db:3306/mydatabase"
    expose:
      - "8080"

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mysql -h db -u root -p'myrootpassword' -e 'SELECT 1 FROM mydatabase.users;'"]
      interval: 10s
      timeout: 3s
      retries: 30

  front:
    build:
      context: front
    volumes:
      - ./front/src:/app/src
      - /app/node_modules
    expose:
      - "3000"

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - front

volumes:
  db_data:
