# Utilisez une image de base OpenJDK
FROM openjdk:11

# Copiez les fichiers de votre application dans l'image
COPY java/matlasAPI-0.0.1-SNAPSHOT.jar .

# Définissez le répertoire de travail
#WORKDIR /usr/src/myapp

# Compilez l'application avec Maven
#RUN ./mvnw package


# Démarrez l'application
CMD ["java", "-jar", "./matlasAPI-0.0.1-SNAPSHOT.jar"]